"""Export approved TestCases → a Postman collection (v2.1) for Newman.

Lets a tester hand the generated plan to `newman run` or the Postman app. Secrets
are NEVER embedded: auth becomes a `{{token_<persona>}}` variable and the host a
`{{baseUrl}}` variable, so the exported file is safe to share and the operator
supplies values in a Postman environment.
"""

from __future__ import annotations

import json

from app.schemas.testcase import TestCase


def export_postman_collection(name: str, tests: list[TestCase]) -> str:
    personas = {t.auth_context.persona for t in tests if t.auth_context.persona != "anonymous"}
    variables = [{"key": "baseUrl", "value": "https://REPLACE-ME"}]
    variables += [{"key": f"token_{p}", "value": ""} for p in sorted(personas)]

    items = [_item(t) for t in tests]
    collection = {
        "info": {
            "name": name,
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "description": "Generated by the API Security Testing Platform. "
                           "Fill baseUrl + token_* in a Postman environment before running.",
        },
        "item": items,
        "variable": variables,
    }
    return json.dumps(collection, indent=2)


def _item(t: TestCase) -> dict:
    path = t.request.path.lstrip("/")
    headers = []
    if t.auth_context.persona != "anonymous" and t.attack_mutation.kind != "drop_auth":
        headers.append({"key": "Authorization",
                        "value": f"Bearer {{{{token_{t.auth_context.persona}}}}}"})
    for k, v in t.request.headers.items():
        if k.lower() != "authorization":
            headers.append({"key": k, "value": str(v)})

    request = {
        "method": t.request.method,
        "header": headers,
        "url": {
            "raw": "{{baseUrl}}/" + path,
            "host": ["{{baseUrl}}"],
            "path": [seg for seg in path.split("/") if seg],
        },
    }
    if t.request.body is not None:
        request["body"] = {"mode": "raw", "raw": json.dumps(t.request.body),
                           "options": {"raw": {"language": "json"}}}

    return {
        "name": f"{t.test_id} · {t.owasp_category.value} · {t.title}",
        "request": request,
        "event": [{
            "listen": "test",
            "script": {"type": "text/javascript", "exec": _assertions(t)},
        }],
    }


def _assertions(t: TestCase) -> list[str]:
    codes = t.expected.status_in
    lines = [
        f"// OWASP {t.owasp_category.value} — a secure system should reject this attack",
        "pm.test('rejected with expected status', function () {",
        f"    pm.expect({json.dumps(codes)}).to.include(pm.response.code);",
        "});",
    ]
    for marker in t.expected.body_must_not_contain:
        lines += [
            "pm.test('no disclosure of protected data', function () {",
            f"    pm.expect(pm.response.text()).to.not.include({json.dumps(marker)});",
            "});",
        ]
    return lines
